// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetDataManually(arg1) {
  return window['go']['main']['App']['GetDataManually'](arg1);
}
